A=int(input("enter the first number: "))
B=int(input("enter the second number: "))
print("the sum of two numbers is: ",A+B)
print("the difference of two numbers is: ",A-B)
print("the product of two numbers is: ",A*B)
print("the division of two numbers is: ",A/B)
print("the remainder of two numbers is: ",A%B)
print("the floor division of two numbers is: ",A//B)
print("the power of two numbers is: ",A**B)